-- 1. Tabel Pengguna
CREATE TABLE IF NOT EXISTS Pengguna (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  kataSandi VARCHAR(255) NOT NULL,
  peran ENUM('ADMIN', 'KEPALA_SEKOLAH', 'GURU', 'SISWA') DEFAULT 'SISWA' NOT NULL,
  isPasswordSementara BOOLEAN DEFAULT TRUE NOT NULL,
  aktif BOOLEAN DEFAULT TRUE NOT NULL,
  sidikJariBrowser TEXT NULL,
  absenDiblokirHingga DATETIME NULL,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB;

-- 2. Tabel Guru
CREATE TABLE IF NOT EXISTS Guru (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nip VARCHAR(30) NULL UNIQUE,
  telepon VARCHAR(20) NULL,
  idPengguna INT NOT NULL UNIQUE,
  isBk BOOLEAN DEFAULT FALSE NOT NULL,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_Guru_Pengguna FOREIGN KEY (idPengguna) REFERENCES Pengguna(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 3. Tabel Kelas
CREATE TABLE IF NOT EXISTS Kelas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(50) NOT NULL UNIQUE,
  tahunAjaran VARCHAR(20) NOT NULL,
  idGuru INT NULL UNIQUE,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_Kelas_Guru FOREIGN KEY (idGuru) REFERENCES Guru(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 4. Tabel Siswa
CREATE TABLE IF NOT EXISTS Siswa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nisn VARCHAR(20) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  idKelas INT NOT NULL,
  teleponOrangTua VARCHAR(20) NOT NULL,
  sedangMagang BOOLEAN DEFAULT FALSE NOT NULL,
  tanggalMulaiMagang DATETIME NULL,
  tanggalSelesaiMagang DATETIME NULL,
  idPengguna INT NOT NULL UNIQUE,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_Siswa_Pengguna FOREIGN KEY (idPengguna) REFERENCES Pengguna(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_Siswa_Kelas FOREIGN KEY (idKelas) REFERENCES Kelas(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 5. Tabel Kehadiran
CREATE TABLE IF NOT EXISTS Kehadiran (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idSiswa INT NOT NULL,
  tanggal DATE NOT NULL,
  tahunAjaran VARCHAR(20) DEFAULT '2024/2025' NOT NULL,
  status ENUM('HADIR', 'TERLAMBAT', 'SAKIT', 'IZIN', 'ALPHA') DEFAULT 'HADIR' NOT NULL,
  waktuMasuk DATETIME NULL,
  latitude DOUBLE NULL,
  longitude DOUBLE NULL,
  dicatatOleh INT NULL,
  catatan VARCHAR(255) NULL,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_Kehadiran_Siswa FOREIGN KEY (idSiswa) REFERENCES Siswa(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_Kehadiran_Pengguna FOREIGN KEY (dicatatOleh) REFERENCES Pengguna(id) ON DELETE SET NULL ON UPDATE CASCADE,
  UNIQUE KEY UK_Kehadiran_Siswa_Tanggal (idSiswa, tanggal),
  INDEX IX_Kehadiran_Tanggal_Status (tanggal, status),
  INDEX IX_Kehadiran_TahunAjaran (tahunAjaran)
) ENGINE=InnoDB;

-- 6. Tabel LogWa
CREATE TABLE IF NOT EXISTS LogWa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idSiswa INT NOT NULL,
  telepon VARCHAR(20) NOT NULL,
  pesan TEXT NOT NULL,
  status ENUM('TERKIRIM', 'GAGAL', 'GAGAL_OFFLINE', 'TERTUNDA') DEFAULT 'TERTUNDA' NOT NULL,
  error TEXT NULL,
  sentAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_LogWa_Siswa FOREIGN KEY (idSiswa) REFERENCES Siswa(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 7. Tabel Pengaturan
CREATE TABLE IF NOT EXISTS Pengaturan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  kunci VARCHAR(100) NOT NULL UNIQUE,
  nilai TEXT NOT NULL,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB;

-- 8. Tabel HariLibur
CREATE TABLE IF NOT EXISTS HariLibur (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tanggal DATE NOT NULL UNIQUE,
  nama VARCHAR(150) NOT NULL,
  isKustom BOOLEAN DEFAULT FALSE NOT NULL,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB;

-- 9. Tabel LogAuditAdmin
CREATE TABLE IF NOT EXISTS LogAuditAdmin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idPengguna INT NOT NULL,
  tindakan VARCHAR(100) NOT NULL,
  target VARCHAR(100) NOT NULL,
  detail TEXT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_LogAuditAdmin_Pengguna FOREIGN KEY (idPengguna) REFERENCES Pengguna(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 10. Tabel LogKonselingBk
CREATE TABLE IF NOT EXISTS LogKonselingBk (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idSiswa INT NOT NULL,
  idBk INT NOT NULL,
  detail TEXT NOT NULL,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_LogKonselingBk_Siswa FOREIGN KEY (idSiswa) REFERENCES Siswa(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_LogKonselingBk_Pengguna FOREIGN KEY (idBk) REFERENCES Pengguna(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 11. Tabel JadwalPiket
CREATE TABLE IF NOT EXISTS JadwalPiket (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hari ENUM('SENIN', 'SELASA', 'RABU', 'KAMIS', 'JUMAT', 'SABTU') NOT NULL,
  idGuru INT NOT NULL,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_JadwalPiket_Guru FOREIGN KEY (idGuru) REFERENCES Guru(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY UK_JadwalPiket_Hari_Guru (hari, idGuru)
) ENGINE=InnoDB;

-- 12. Tabel DispensasiKeterlambatan
CREATE TABLE IF NOT EXISTS DispensasiKeterlambatan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idSiswa INT NOT NULL,
  tanggal DATE NOT NULL,
  alasan TEXT NOT NULL,
  fotoBukti VARCHAR(255) NULL,
  status ENUM('MENUNGGU', 'DISETUJUI', 'DITOLAK') DEFAULT 'MENUNGGU' NOT NULL,
  disetujuiOleh INT NULL,
  dibuatPada DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  diubahPada DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_Dispensasi_Siswa FOREIGN KEY (idSiswa) REFERENCES Siswa(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_Dispensasi_Pengguna FOREIGN KEY (disetujuiOleh) REFERENCES Pengguna(id) ON DELETE SET NULL ON UPDATE CASCADE,
  UNIQUE KEY UK_Dispensasi_Siswa_Tanggal (idSiswa, tanggal)
) ENGINE=InnoDB;

